### ISSUE TITLE
No steps to import the modules and work with it.

### ISSUE THREAD

**Issue by uncommonthinker** [XayOn/pyrcrack#1]
Can you give a detailed step by step instruction as to how to use the module in my python code?

**Comment by llazzaro** [comment]
Just check the source code.
Here is an example on how to use Airodump, I read the code in https://github.com/XayOn/pyrcrack/blob/master/pyrcrack/scanning.py

Good luck

```python
from pyrcrack.scanning import Airodump
kwargs = {
            'output-format': 'csv,pcap',
            'channel': 1,
            'write': '/tmp/capture'
        }
airodump_process = Airodump(self.iface, **kwargs)
airodump_process.start()
```

**Comment by XayOn** [comment]
And have in account that this has not been in active development for a
while. Sorry

PRs are welcome of course 😀😉

**Comment by XayOn** [comment]
Hey @uncommonthinker @llazzaro FYI pyrcrack now currently has improved quite a bit, and I'm working on a better documentation set.

I'm reopening this issue and hijacking it a bit to document it.

**Comment by ChristianGuardDog** [comment]
Could you please explain to me how to fix this import error
![image](https://user-images.githubusercontent.com/96301338/166294302-8d2f8b33-2fb3-41ec-a89e-12d3dcee219a.png)
It is the Airelay example

**Comment by XayOn** [comment]
@Kriz1618 that shouldn't happen.

Are you, by any chance, executing the examples from the develop branch but having a stable release installed? 😃 

As you have pyrcrack installed directly as root, I can guess you did a "sudo pip install pyrcrack", instead of installing from the repo.

That's perfectly valid, except that you need to use the examples for that release, you can't use modern examples on an older release. I don't know wich release you installed, so you need to figure that out, download the relase zip, and run the examples from there.

It's either that, installing it with poetry from the repo, (sudo -E - is useful for this), or waiting for the next major release and upgrade everything.

**Comment by Kriz1618** [comment]
**Yes, I've installed it with sudo pip3**

**Comment by XayOn** [comment]
@Kriz1618 Then, as I said, it wouldn't have worked because you were using unreleased examples with a released version.
I've set up "main" branch as the public main branch so that confusion shouldn't happen again, main branch and doc will be synced with latest released version from now on.

**Comment by XayOn** [comment]
I'm closing this issue and will be opening a new one for an improved documentation
